BasePlantilla/Controllers/MetricasCapacitacionesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaGestionTalentoHumano.Data;
using SistemaGestionTalentoHumano.Models;
using Newtonsoft.Json;

namespace SistemaGestionTalentoHumano.Controllers
{
    public class MetricasCapacitacionesController : Controller
    {
        private readonly TalentoHumanoDbContext _context;

        public MetricasCapacitacionesController(TalentoHumanoDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public string CargaDatosXMes()
        {
            var capacitaciones = _context.Capacitacion
                                    .Include(x => x.CapacitacionEmpleado)
                                    .Select(x => new { Mes = x.FechaInicio.Month, Cuenta = x.CapacitacionEmpleado.Count() });
                
            var labels = new List<string>();
            var data = new List<string>();

            foreach (var capacitacion in capacitaciones) {
                labels.Add(capacitacion.Mes.ToString());
                data.Add(capacitacion.Cuenta.ToString());
            }

            var datos = new Dictionary<string, List<string>>
            {
                {"labels", labels},
                {"data", data}
            };

            return JsonConvert.SerializeObject(datos);
        }
    }
}

BasePlantilla/Views/MetricasCapacitaciones/Index.cshtml
@*@model IEnumerable<SistemaGestionTalentoHumano.Controllers.MetricasCapacitacionesController>*@


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Area Chart</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="chart">
                            <canvas id="areaChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">

                <div class="card card-danger">
                    <div class="card-header">
                        <h3 class="card-title">Donut Chart</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <canvas id="donutChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script>
        cargaDatos();

        function cargaDatos() {
            cargaTotalCursosXMes();
        }

        function cargaTotalCursosXMes() {

            let datos;

            $.ajax({
                async: false,
                global: false,
                url: '@Url.Action("CargaDatosXMes", "MetricasCapacitaciones")',
                dataType: "json",
                success: function (data) {
                    datos = data;
                }
            });

            var areaChartCanvas = $('#areaChart').get(0).getContext('2d')

            var areaChartData = {
                labels: datos['labels'],
                datasets: [
                    {
                        label: datos['labels'],
                        backgroundColor: 'rgba(60,141,188,0.9)',
                        borderColor: 'rgba(60,141,188,0.8)',
                        pointRadius: false,
                        pointColor: '#3b8bba',
                        pointStrokeColor: 'rgba(60,141,188,1)',
                        pointHighlightFill: '#fff',
                        pointHighlightStroke: 'rgba(60,141,188,1)',
                        data: datos['data']
                    },
                ]
            }

            var barChartOptions = {
                responsive: true,
                maintainAspectRatio: false,
                datasetFill: false
            }

            new Chart(areaChartCanvas, {
                type: "bar",
                data: areaChartData,
                options: barChartOptions
            });
        }

        $(function () {

            // This will get the first returned node in the jQuery collection.


            //-------------
            //- DONUT CHART -
            //-------------
            // Get context with jQuery - using jQuery's .get() method.
            var donutChartCanvas = $('#donutChart').get(0).getContext('2d')
            var donutData = {
                labels: [
                    'Chrome',
                    'IE',
                    'FireFox',
                    'Safari',
                    'Opera',
                    'Navigator',
                ],
                datasets: [
                    {
                        data: [700, 500, 400, 600, 300, 100],
                        backgroundColor: ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc', '#d2d6de'],
                    }
                ]
            }
            var donutOptions = {
                maintainAspectRatio: false,
                responsive: true,
            }
            //Create pie or douhnut chart
            // You can switch between pie and douhnut using the method below.
            new Chart(donutChartCanvas, {
                type: 'doughnut',
                data: donutData,
                options: donutOptions
            })
        })
    </script>
}